# Numpy - Exercise

In [54]:
!pip install -r requirements.txt

In [30]:
import numpy as np
import matplotlib.image as mpimg
import pandas as pd

## Bài tập 1: Numpy Cơ Bản

### Câu hỏi 1: Câu nào sau đây là đúng để tạo mảng 1 chiều từ 0 đến 9
> A

In [6]:
arr = np.arange(0, 10 , 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Câu hỏi 2: Cách tạo một mảng boolean 3x3 với tất cả giá trị là True
> D

In [3]:
arr = np.ones((3 ,3) ) > 0
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
arr = np.ones((3, 3) , dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
arr = np.full((3, 3) , fill_value=True , dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Câu hỏi 3: Kết quả của đoạn code sau đây:
> A

In [9]:
arr = np.arange(0, 10)
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

### Câu hỏi 4: Kết quả của đoạn code sau đây:
> B

In [10]:
arr = np.arange(0, 10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Câu hỏi 5: Kết quả của đoạn code sau đây:
> B

In [11]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Câu hỏi 6: Kết quả của đoạn code sau đây:
> A

In [12]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Câu hỏi 7: Kết quả của đoạn code sau đây:
> C

In [13]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Câu hỏi 8: Kết quả của đoạn code sau đây:
> A

In [14]:
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


### Câu hỏi 9: Kết quả của đoạn code sau đây:
> C

In [15]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a>=5) & (a<=10))
a[index]

array([ 6,  9, 10])

### Câu hỏi 10: Kết quả của đoạn code sau đây:
> D

In [16]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

b = np.array([6, 3, 4, 8, 9, 7, 1])
a = np.array([5, 7, 9, 8, 6, 4, 5])

pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

### Câu hỏi 11: Kết quả của đoạn code sau đây:
> A

In [17]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

np.where(a < b , b, a)

array([6, 7, 9, 8, 9, 7, 5])

## Bài tập 2: Xử lý ảnh

In [57]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB -O data/dog.jpeg

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: d:\AIO2024\study_project\AIO2024_Exercises\week01_numpy\data\dog.jpeg

  0%|          | 0.00/33.7k [00:00<?, ?B/s]
100%|██████████| 33.7k/33.7k [00:00<00:00, 1.35MB/s]


In [ ]:
img = mpimg.imread('dog.jpeg')

### Câu hỏi 12: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào phương pháp Lightness:
> A

In [58]:
gray_img_01 = (np.max(img, axis=2) + np.min(img, axis=2))/2
gray_img_01[0,0]

102.5

### Câu hỏi 13: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào phương pháp Average:
> A

In [23]:
gray_img_02 = np.mean(img, axis=2)
gray_img_02[0 , 0]

107.66666666666667

### Câu hỏi 14: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào phương pháp Luminosity:
> C

In [25]:
gray_img_03 = 0.21 * img[:, :, 0] + 0.72 * img[:, :, 1] + 0.07 * img[:, :, 2]
gray_img_03[0 , 0]

126.22999999999999

## Bài tập 3: Phân tích dữ liệu dạng bảng

In [60]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq -O data/advertising.csv

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: d:\AIO2024\study_project\AIO2024_Exercises\week01_numpy\advertising.csv

  0%|          | 0.00/4.06k [00:00<?, ?B/s]
100%|██████████| 4.06k/4.06k [00:00<?, ?B/s]


In [55]:
df = pd.read_csv ('data/advertising.csv')
df.head(5)

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [32]:
data = df.to_numpy()

### Câu hỏi 15: Lấy giá trị lớn nhất và chỉ mục tương ứng của nó trên cột Sales:
> C

In [33]:
max_value = data.max(axis=0)[3]
max_index = data.argmax(axis=0)[3]
print(f"Max: {max_value} - Index: {max_index}")

Max: 27.0 - Index: 175


### Câu hỏi 16: Giá trị trung bình của cột TV là:
> B

In [34]:
tv_mean = np.mean(data, axis=0)[0]
tv_mean

147.0425

### Câu hỏi 17: Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20 là:
> A

In [35]:
x = data[data[:, 3] >= 20]
len(x)

40

### Câu hỏi 18: Tính giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng trên cột Sales lớn hơn hoặc bằng 15:
> B

In [36]:
x = data[data[:, 3] >= 15]
radio_mean = np.mean(x, axis=0)[1]
radio_mean

26.222935779816517

### Câu hỏi 19: Tính tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn giá trị trung bình của cột Newspaper:
> C

In [39]:
newspaper_mean = np.mean(data, axis=0)[2]
x = data[data[:, 2] > newspaper_mean]
x_sum = np.sum(x[:,3], axis=0)
x_sum

1405.1

### Câu hỏi 20: Gọi giá trị trung bình của cột Sales là A. Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: nếu giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là Average. Sau đó in ra kết quả scores[7:10]
> C

In [44]:
def cal_scores(x, A):
    if x > A:
        return "Good"
    elif  x < A:
        return "Bad"
    else:
        return "Average"

A = np.mean(data[:, 3])
v_cal_scores  = np.vectorize(cal_scores)
scores = v_cal_scores(data[:, 3], A)
scores[7:10]

array(['Bad', 'Bad', 'Good'], dtype='<U4')

### Câu hỏi 21: Gọi giá trị trên cột Sales gần nhất với giá trị trung bình cũng chính cột Sales là A. Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: nếu giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là Average. Sau đó in ra kết quả scores[7:10]
> C

In [45]:
A = np.mean(data[:, 3])
scores = np.empty(data.shape[0], dtype=object)

for i in range(data.shape[0]):
    if data[i, 3] > A:
        scores[i] = 'Good'
    elif data[i, 3] < A:
        scores[i] = 'Bad'
    else:
        scores[i] = 'Average'
scores[7:10]

array(['Bad', 'Bad', 'Good'], dtype='<U7')